@startuml
class Chemin {
    +CheminListeEleve : string
    +CheminDossierListeEleve : string 
    +CheminPhotoEleve : string
    +CheminEdtClassique : string
    +CheminFaceCarte : string
    +CheminEdtPerso : string
    +CheminEdt : string
    +setCheminImportationFaceCarte() : string
    +setCheminImportationFichierExcel() : string
    +setCheminImportationFichierPdf() : string
    +setCheminImportationDossier() : string
}

class ConnectDb {
    +init() : void
    +connect() : SQLiteConnection
    +SelectRow() : string
    +DbData(db : string) : bool
}

class CopieImage {
    +CopierImages(cheminSource : string, cheminDestination : string) : void
}

class Couleur {
    +setCouleurFenetre(fenetre : Form) : void
    +setCouleurPanel(panel : Panel) : void
    +setCouleurGroupeBox(groupeBox : GroupBox) : void
    +setCouleurBouton(btn : Button) : void
    +setCouleurAutre(controle : Control) : void
    +setCouleurTextBox(txt : TextBox) : void 
    +setCouleurListBox(lst : ListBox) : void
    +changement_state_btn(sender : object, e : EventArgs) : void
}

class Globale {
    +EleveImpr : bool
    +TestBordure : bool
    +PositionPhotoClassique : bool 
    +Owner : string
    +Repo : string
    +FileName : string
    {static} +LblDate : Label
    {static} +LblCount : Label
    {enum} CodeCas
    +Cas : CodeCas
    +ListeCas : List<CodeCas>
    +txtPdf : string
    +Classe : int
    +Connexion : Form
    +EstConnecte : bool
    +NomUtilisateur : string
    +Classes6Eme : List<string>
    +Classes5Eme : List<string>
    +Classes4Eme : List<string>
    +Classes3Eme : List<string>
    +ClassesInconnue : List<string>
    +ListeEleve : List<Eleve>
    +ListeEleveImpr : List<Eleve>  
    +ListeEleveSansPhoto : List<Eleve>
    +ListeElevesString : List<string>
    +EstEnModeSombre : bool
    +CouleurDeFondClaire : List<int>
    +CouleurDuTexteClaire : List<int>
    +CouleurBandeauxClaire : List<int>
    +CouleurBoutonsClaire : List<int>
    +CouleurTextBoxClaire : List<int>
    +CouleurBoutonOffClaire : List<int>
    +CouleurDeFondSombre : List<int>
    +CouleurDuTexteSombre : List<int>
    +CouleurBandeauxSombre : List<int>
    +CouleurBoutonsSombre : List<int>
    +CouleurTextBoxSombre : List<int>
    +CouleurBoutonOffSombre : List<int>
    +Actuelle : Form
    +Accueil : Form  
    +Version : string
    +VersionDate : string
    +CheminTexte : string
    +CheminPdf : string
    +CheminPhoto : string
    +CheminEdtClassique : string
    +CheminFaceCarte : string
    +GitPoule : bool
    +PbPhoto : PictureBox
    +ListeSauvegardeProvisoire : Tuple<PictureBox, PictureBox, PictureBox, TextBox, TextBox>
    +ListeEleves6Eme : List<Eleve>
    +ListeEleves5Eme : List<Eleve>
    +ListeEleves4Eme : List<Eleve>
    +ListeEleves3Eme : List<Eleve>
    +MotsDePasseChiffrement : string
    +ChangementMotDePasseChiffrement : bool
    +ConnectionBdd : bool
    +ActionEnCours : bool
}

Eleve ..> Globale

@enduml
